# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
#obsidian_folder_path_str: ',/' 

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: 'notes/Home.md'

copy_vault_to_tempdir: true
copy_vault_to_tempdir_method: default

html_url_prefix: '/notes'

site_name: CheerfulP's Notes
navbar_links:
  - name: Home
    link: index.html
  - name: GSoC 2024
    link: GSOC/GSOC.html

toggles:
  # If this is false only the entrypoint and all its links (recursively) are processed
  # if true all the notes will be processed
  process_all: False
  features:
    styling:
      layout: documentation # documentation, tabs, minimal 
    rss:
      enabled: true
      host_root: 'https://cheerfulpianissimo.github.io/'
      channel:
        title: "CheerfulP's Notes"
        website_link: 'cheerfulpianissimo.github.io'
        description: "CheerfulPianissimo's Notebook/Blog"
        language_code: en-us
        managing_editor: "na"
        web_master: "na"
    table_of_contents:
      add_toc_when_missing: true
    side_pane:
      left_pane:
        enabled: true
        width: 16rem
        contents: dir_tree
        content_args:
          rel_path: index.html
          div_selector: .content
          strip_sub_divs:
            - .toc
      right_pane:
        enabled: true
        width: 16rem
        contents: toc
        content_args:
          rel_path: index.html
          div_selector: .content
          strip_sub_divs:
            - .toc
