name: Publish to gh-pages branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build and Push
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          path: notes

      - name: Install dependencies and run build
        run: |
          cd ${{ github.workspace }}
          pip install --upgrade pip
          pip install git+https://github.com/obsidian-html/obsidian-html@cafcb03
          obsidianhtml convert -i notes/config.yaml -v
          mv output/html output/notes #handle the site being on /notes
          mv notes/redirect.html output/index.html
          touch output/.nojekyll

      - name: Publish to Github Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: output # The directory where your assets are generated
          SQUASH_HISTORY: true # Squashes branch history to avoid file buildup
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
